image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-browser

tasks:
  - init:
      cp .env.sample .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env
    command: >
      php -S 0.0.0.0:8000 -t web
